package com.example.gymlog2

object DataProvider {
    data class ExerciseDef(val name: String, val group: String, val equipment: String = "")

    val grupeMusculare = listOf("Piept", "Spate", "Umeri", "Biceps", "Triceps", "Abdomen", "Picioare", "Fese", "Gambe", "Antebrate", "Gat & Trapezi")

    val exercitiiPeGrupa = mapOf(
        "Piept" to listOf(
            ExerciseDefinition("Bench Press", "Piept", "Barbell"),
            ExerciseDefinition("Incline Bench Press", "Piept", "Barbell"),
            ExerciseDefinition("Decline Bench Press", "Piept", "Barbell"),
            ExerciseDefinition("Dumbbell Fly", "Piept", "Dumbbells"),
            ExerciseDefinition("Cable Crossover", "Piept", "Cable"),
            ExerciseDefinition("Push-Up", "Piept", "Bodyweight"),
            ExerciseDefinition("Dumbbell Bench Press", "Piept", "Dumbbells"),
            ExerciseDefinition("Dumbbell Incline Bench Press", "Piept", "Dumbbells"),
            ExerciseDefinition("Dumbbell Decline Bench Press", "Piept", "Dumbbells"),
            ExerciseDefinition("Dumbbell Pullover", "Piept", "Dumbbells"),
            ExerciseDefinition("Dumbbell Incline Fly", "Piept", "Dumbbells"),
            ExerciseDefinition("Dumbbell Decline Fly", "Piept", "Dumbbells"),
            ExerciseDefinition("Cable Incline Fly", "Piept", "Cable"),
            ExerciseDefinition("Cable Decline Fly", "Piept", "Cable"),
            ExerciseDefinition("Cable Bench Press", "Piept", "Cable"),
            ExerciseDefinition("Chest Dip", "Piept", "Bodyweight"),
            ExerciseDefinition("Incline Push-Up", "Piept", "Bodyweight"),
            ExerciseDefinition("Decline Push-Up", "Piept", "Bodyweight"),
            ExerciseDefinition("Barbell Guillotine Bench Press", "Piept", "Barbell"),
            ExerciseDefinition("Clap Push Up", "Piept", "Bodyweight"),
            ExerciseDefinition("Cable Middle Fly", "Piept", "Cable"),
            ExerciseDefinition("Wide Push Up", "Piept", "Bodyweight"),
            ExerciseDefinition("Plyo Push Up", "Piept", "Bodyweight"),
            ExerciseDefinition("Dumbbell Straight Arm Pullover", "Piept", "Dumbbells")
        ),
        "Spate" to listOf(
            ExerciseDefinition("Deadlift", "Spate", "Barbell"),
            ExerciseDefinition("Barbell Row", "Spate", "Barbell"),
            ExerciseDefinition("Pull-Up", "Spate", "Bodyweight"),
            ExerciseDefinition("Lat Pulldown", "Spate", "Cable"),
            ExerciseDefinition("Seated Cable Row", "Spate", "Cable"),
            ExerciseDefinition("T-Bar Row", "Spate", "Barbell"),
            ExerciseDefinition("Chin-Up", "Spate", "Bodyweight"),
            ExerciseDefinition("Wide Grip Pull-Up", "Spate", "Bodyweight"),
            ExerciseDefinition("Cable Straight Arm Pulldown", "Spate", "Cable"),
            ExerciseDefinition("Dumbbell One Arm Row", "Spate", "Dumbbells"),
            ExerciseDefinition("Inverted Row", "Spate", "Bodyweight"),
            ExerciseDefinition("Cable Underhand Pulldown", "Spate", "Cable"),
            ExerciseDefinition("Cable Lateral Pulldown", "Spate", "Cable"),
            ExerciseDefinition("Cable High Row", "Spate", "Cable"),
            ExerciseDefinition("Barbell Pendlay Row", "Spate", "Barbell"),
            ExerciseDefinition("Dumbbell Row", "Spate", "Dumbbells"),
            ExerciseDefinition("Cable Seated Wide-Grip Row", "Spate", "Cable")
        ),
        "Umeri" to listOf(
            ExerciseDefinition("Overhead Press", "Umeri", "Barbell"),
            ExerciseDefinition("Lateral Raise", "Umeri", "Dumbbells"),
            ExerciseDefinition("Front Raise", "Umeri", "Dumbbells"),
            ExerciseDefinition("Face Pull", "Umeri", "Cable"),
            ExerciseDefinition("Arnold Press", "Umeri", "Dumbbells"),
            ExerciseDefinition("Rear Delt Fly", "Umeri", "Dumbbells"),
            ExerciseDefinition("Dumbbell Shoulder Press", "Umeri", "Dumbbells"),
            ExerciseDefinition("Seated Dumbbell Press", "Umeri", "Dumbbells"),
            ExerciseDefinition("Cable Lateral Raise", "Umeri", "Cable"),
            ExerciseDefinition("Barbell Upright Row", "Umeri", "Barbell"),
            ExerciseDefinition("Cable Front Raise", "Umeri", "Cable"),
            ExerciseDefinition("Dumbbell Push Press", "Umeri", "Dumbbells"),
            ExerciseDefinition("Cable Shoulder Press", "Umeri", "Cable"),
            ExerciseDefinition("Dumbbell Cuban Press", "Umeri", "Dumbbells"),
            ExerciseDefinition("Dumbbell Lateral Raise", "Umeri", "Dumbbells"),
            ExerciseDefinition("Cable Seated Rear Lateral Raise", "Umeri", "Cable")
        ),
        "Biceps" to listOf(
            ExerciseDefinition("Barbell Curl", "Biceps", "Barbell"),
            ExerciseDefinition("Hammer Curl", "Biceps", "Dumbbells"),
            ExerciseDefinition("Preacher Curl", "Biceps", "Dumbbells"),
            ExerciseDefinition("Concentration Curl", "Biceps", "Dumbbells"),
            ExerciseDefinition("Cable Bicep Curl", "Biceps", "Cable"),
            ExerciseDefinition("Dumbbell Incline Curl", "Biceps", "Dumbbells"),
            ExerciseDefinition("EZ Bar Curl", "Biceps", "EZ Bar"),
            ExerciseDefinition("Barbell Reverse Curl", "Biceps", "Barbell"),
            ExerciseDefinition("Cable Hammer Curl", "Biceps", "Cable"),
            ExerciseDefinition("EZ Bar Preacher Curl", "Biceps", "EZ Bar"),
            ExerciseDefinition("Dumbbell Preacher Curl", "Biceps", "Dumbbells"),
            ExerciseDefinition("Dumbbell Alternate Biceps Curl", "Biceps", "Dumbbells"),
            ExerciseDefinition("EZ Bar Reverse Curl", "Biceps", "EZ Bar"),
            ExerciseDefinition("Dumbbell Bicep Curl", "Biceps", "Dumbbells")
        ),
        "Triceps" to listOf(
            ExerciseDefinition("Tricep Pushdown", "Triceps", "Cable"),
            ExerciseDefinition("Skull Crusher", "Triceps", "Barbell"),
            ExerciseDefinition("Dips", "Triceps", "Bodyweight"),
            ExerciseDefinition("Close-Grip Bench Press", "Triceps", "Barbell"),
            ExerciseDefinition("Dumbbell Kickback", "Triceps", "Dumbbells"),
            ExerciseDefinition("Cable Overhead Tricep Extension", "Triceps", "Cable"),
            ExerciseDefinition("Overhead Tricep Extension", "Triceps", "Dumbbells"),
            ExerciseDefinition("Diamond Push-Up", "Triceps", "Bodyweight"),
            ExerciseDefinition("Close-Grip Push-Up", "Triceps", "Bodyweight"),
            ExerciseDefinition("Bench Dip", "Triceps", "Bodyweight"),
            ExerciseDefinition("EZ Bar Standing French Press", "Triceps", "EZ Bar"),
            ExerciseDefinition("EZ Bar JM Bench Press", "Triceps", "EZ Bar"),
            ExerciseDefinition("Cable Tricep Pushdown V-Bar", "Triceps", "Cable")
        ),
        "Abdomen" to listOf(
            ExerciseDefinition("Plank", "Abdomen", "Bodyweight"),
            ExerciseDefinition("Crunch", "Abdomen", "Bodyweight"),
            ExerciseDefinition("Russian Twist", "Abdomen", "Bodyweight"),
            ExerciseDefinition("Hanging Leg Raise", "Abdomen", "Bodyweight"),
            ExerciseDefinition("Ab Rollout", "Abdomen", "Cable"),
            ExerciseDefinition("Cable Woodchop", "Abdomen", "Cable"),
            ExerciseDefinition("Dead Bug", "Abdomen", "Bodyweight"),
            ExerciseDefinition("Reverse Crunch", "Abdomen", "Bodyweight"),
            ExerciseDefinition("Side Plank", "Abdomen", "Bodyweight"),
            ExerciseDefinition("Lying Leg Raise", "Abdomen", "Bodyweight"),
            ExerciseDefinition("Cable Crunch", "Abdomen", "Cable"),
            ExerciseDefinition("Cross Body Crunch", "Abdomen", "Bodyweight"),
            ExerciseDefinition("Sit-Up", "Abdomen", "Bodyweight"),
            ExerciseDefinition("Seated Leg Raise", "Abdomen", "Bodyweight"),
            ExerciseDefinition("Decline Sit-Up", "Abdomen", "Bodyweight"),
            ExerciseDefinition("Hanging Knee Raise", "Abdomen", "Bodyweight"),
            ExerciseDefinition("Cable Seated Twist", "Abdomen", "Cable"),
            ExerciseDefinition("Jackknife Sit-Up", "Abdomen", "Bodyweight"),
            ExerciseDefinition("Front Plank With Twist", "Abdomen", "Bodyweight")
        ),
        "Picioare" to listOf(
            ExerciseDefinition("Squat", "Picioare", "Barbell"),
            ExerciseDefinition("Leg Press", "Picioare", "Machine"),
            ExerciseDefinition("Romanian Deadlift", "Picioare", "Barbell"),
            ExerciseDefinition("Bulgarian Split Squat", "Picioare", "Dumbbells"),
            ExerciseDefinition("Hip Thrust", "Picioare", "Dumbbells"),
            ExerciseDefinition("Barbell Front Squat", "Picioare", "Barbell"),
            ExerciseDefinition("Barbell Lunge", "Picioare", "Barbell"),
            ExerciseDefinition("Barbell Good Morning", "Picioare", "Barbell"),
            ExerciseDefinition("Dumbbell Lunge", "Picioare", "Dumbbells"),
            ExerciseDefinition("Dumbbell Goblet Squat", "Picioare", "Dumbbells"),
            ExerciseDefinition("Dumbbell Step-Up", "Picioare", "Dumbbells"),
            ExerciseDefinition("Dumbbell Romanian Deadlift", "Picioare", "Dumbbells"),
            ExerciseDefinition("Jump Squat", "Picioare", "Bodyweight"),
            ExerciseDefinition("Walking Lunge", "Picioare", "Bodyweight"),
            ExerciseDefinition("Kettlebell Swing", "Picioare", "Kettlebell"),
            ExerciseDefinition("Kettlebell Goblet Squat", "Picioare", "Kettlebell"),
            ExerciseDefinition("Single Leg Deadlift", "Picioare", "Dumbbells"),
            ExerciseDefinition("Barbell Sumo Deadlift", "Picioare", "Barbell"),
            ExerciseDefinition("Barbell Reverse Lunge", "Picioare", "Barbell"),
            ExerciseDefinition("Barbell Step-Up", "Picioare", "Barbell"),
            ExerciseDefinition("Sled Hack Squat", "Picioare", "Sled Machine"),
            ExerciseDefinition("Kettlebell Turkish Get Up", "Picioare", "Kettlebell"),
            ExerciseDefinition("Kettlebell Front Squat", "Picioare", "Kettlebell"),
            ExerciseDefinition("Split Squat", "Picioare", "Bodyweight")
        ),
        "Fese" to listOf(
            ExerciseDefinition("Hip Thrust", "Fese", "Dumbbells"),
            ExerciseDefinition("Glute Bridge", "Fese", "Bodyweight"),
            ExerciseDefinition("Cable Kickback", "Fese", "Cable"),
            ExerciseDefinition("Sumo Deadlift", "Fese", "Bodyweight"),
            ExerciseDefinition("Bulgarian Split Squat", "Fese", "Dumbbells"),
            ExerciseDefinition("Bodyweight Glute Bridge", "Fese", "Bodyweight"),
            ExerciseDefinition("Barbell Hip Thrust", "Fese", "Barbell"),
            ExerciseDefinition("Glute Bridge March", "Fese", "Bodyweight"),
            ExerciseDefinition("Kettlebell Deadlift", "Fese", "Kettlebell")
        ),
        "Gambe" to listOf(
            ExerciseDefinition("Leg Curl", "Gambe", "Machine"),
            ExerciseDefinition("Leg Extension", "Gambe", "Machine"),
            ExerciseDefinition("Calf Raise", "Gambe", "Machine"),
            ExerciseDefinition("Hack Squat", "Gambe", "Machine"),
            ExerciseDefinition("Leg Press", "Gambe", "Machine"),
            ExerciseDefinition("Standing Calf Raise", "Gambe", "Bodyweight"),
            ExerciseDefinition("Seated Calf Raise", "Gambe", "Machine"),
            ExerciseDefinition("Donkey Calf Raise", "Gambe", "Bodyweight"),
            ExerciseDefinition("Bodyweight Standing Calf Raise", "Gambe", "Bodyweight")
        ),
        "Antebrate" to listOf(
            ExerciseDefinition("Barbell Wrist Curl", "Antebrate", "Barbell"),
            ExerciseDefinition("Barbell Reverse Wrist Curl", "Antebrate", "Barbell"),
            ExerciseDefinition("Farmer's Walk", "Antebrate", "Dumbbells"),
            ExerciseDefinition("Finger Curls", "Antebrate", "Barbell"),
            ExerciseDefinition("Dumbbell Wrist Curl", "Antebrate", "Dumbbells"),
            ExerciseDefinition("Cable Wrist Curl", "Antebrate", "Cable"),
            ExerciseDefinition("Dumbbell Reverse Wrist Curl", "Antebrate", "Dumbbells")
        ),
        "Gat & Trapezi" to listOf(
            ExerciseDefinition("Neck Side Stretch", "Gat & Trapezi", "Bodyweight"),
            ExerciseDefinition("Side Push Neck Stretch", "Gat & Trapezi", "Bodyweight"),
            ExerciseDefinition("Barbell Shrugs", "Gat & Trapezi", "Barbell"),
            ExerciseDefinition("Dumbbell Shrugs", "Gat & Trapezi", "Dumbbells"),
            ExerciseDefinition("Cable Shrugs", "Gat & Trapezi", "Cable"),
            ExerciseDefinition("Barbell Shrug", "Gat & Trapezi", "Barbell"),
            ExerciseDefinition("Smith Machine Shrugs", "Gat & Trapezi", "Smith Machine")
        )
    )

    val templateuri = listOf(
        WorkoutTemplate("Push", listOf(
            TemplateExercise("Piept", ExerciseDefinition("Bench Press", "Piept", "Barbell")),
            TemplateExercise("Piept", ExerciseDefinition("Incline Bench Press", "Piept", "Barbell")),
            TemplateExercise("Piept", ExerciseDefinition("Dumbbell Fly", "Piept", "Dumbbells")),
            TemplateExercise("Umeri", ExerciseDefinition("Overhead Press", "Umeri", "Barbell")),
            TemplateExercise("Umeri", ExerciseDefinition("Lateral Raise", "Umeri", "Dumbbells")),
            TemplateExercise("Triceps", ExerciseDefinition("Tricep Pushdown", "Triceps", "Cable"))
        )),
        WorkoutTemplate("Pull", listOf(
            TemplateExercise("Spate", ExerciseDefinition("Deadlift", "Spate", "Barbell")),
            TemplateExercise("Spate", ExerciseDefinition("Barbell Row", "Spate", "Barbell")),
            TemplateExercise("Spate", ExerciseDefinition("Pull-Up", "Spate", "Bodyweight")),
            TemplateExercise("Spate", ExerciseDefinition("Lat Pulldown", "Spate", "Cable")),
            TemplateExercise("Gat & Trapezi", ExerciseDefinition("Barbell Shrugs", "Gat & Trapezi", "Barbell")),
            TemplateExercise("Gat & Trapezi", ExerciseDefinition("Dumbbell Shrugs", "Gat & Trapezi", "Dumbbells")),
            TemplateExercise("Biceps", ExerciseDefinition("Barbell Curl", "Biceps", "Barbell")),
            TemplateExercise("Umeri", ExerciseDefinition("Face Pull", "Umeri", "Cable"))
        )),
        WorkoutTemplate("Legs", listOf(
            TemplateExercise("Picioare", ExerciseDefinition("Squat", "Picioare", "Barbell")),
            TemplateExercise("Picioare", ExerciseDefinition("Romanian Deadlift", "Picioare", "Barbell")),
            TemplateExercise("Picioare", ExerciseDefinition("Leg Press", "Picioare", "Machine")),
            TemplateExercise("Gambe", ExerciseDefinition("Leg Curl", "Gambe", "Machine")),
            TemplateExercise("Gambe", ExerciseDefinition("Leg Extension", "Gambe", "Machine")),
            TemplateExercise("Gambe", ExerciseDefinition("Calf Raise", "Gambe", "Machine"))
        )),
        WorkoutTemplate("Upper", listOf(
            TemplateExercise("Piept", ExerciseDefinition("Bench Press", "Piept", "Barbell")),
            TemplateExercise("Spate", ExerciseDefinition("Barbell Row", "Spate", "Barbell")),
            TemplateExercise("Umeri", ExerciseDefinition("Overhead Press", "Umeri", "Barbell")),
            TemplateExercise("Gat & Trapezi", ExerciseDefinition("Dumbbell Shrugs", "Gat & Trapezi", "Dumbbells")),
            TemplateExercise("Biceps", ExerciseDefinition("Barbell Curl", "Biceps", "Barbell")),
            TemplateExercise("Triceps", ExerciseDefinition("Tricep Pushdown", "Triceps", "Cable"))
        )),
        WorkoutTemplate("Full Body", listOf(
            TemplateExercise("Piept", ExerciseDefinition("Bench Press", "Piept", "Barbell")),
            TemplateExercise("Spate", ExerciseDefinition("Barbell Row", "Spate", "Barbell")),
            TemplateExercise("Picioare", ExerciseDefinition("Squat", "Picioare", "Barbell")),
            TemplateExercise("Umeri", ExerciseDefinition("Overhead Press", "Umeri", "Barbell")),
            TemplateExercise("Gat & Trapezi", ExerciseDefinition("Barbell Shrugs", "Gat & Trapezi", "Barbell")),
            TemplateExercise("Abdomen", ExerciseDefinition("Plank", "Abdomen", "Bodyweight"))
        ))
    )

    val defaultExercises: List<ExerciseDef> = listOf(
        ExerciseDef("Bench Press", "Chest", "Barbell"),
        ExerciseDef("Incline Bench Press", "Chest", "Barbell"),
        ExerciseDef("Decline Bench Press", "Chest", "Barbell"),
        ExerciseDef("Dumbbell Fly", "Chest", "Dumbbells"),
        ExerciseDef("Cable Crossover", "Chest", "Cable"),
        ExerciseDef("Push-Up", "Chest", "Bodyweight"),
        ExerciseDef("Dumbbell Bench Press", "Chest", "Dumbbells"),
        ExerciseDef("Dumbbell Incline Bench Press", "Chest", "Dumbbells"),
        ExerciseDef("Dumbbell Decline Bench Press", "Chest", "Dumbbells"),
        ExerciseDef("Dumbbell Pullover", "Chest", "Dumbbells"),
        ExerciseDef("Dumbbell Incline Fly", "Chest", "Dumbbells"),
        ExerciseDef("Dumbbell Decline Fly", "Chest", "Dumbbells"),
        ExerciseDef("Cable Incline Fly", "Chest", "Cable"),
        ExerciseDef("Cable Decline Fly", "Chest", "Cable"),
        ExerciseDef("Cable Bench Press", "Chest", "Cable"),
        ExerciseDef("Chest Dip", "Chest", "Bodyweight"),
        ExerciseDef("Incline Push-Up", "Chest", "Bodyweight"),
        ExerciseDef("Decline Push-Up", "Chest", "Bodyweight"),
        ExerciseDef("Barbell Guillotine Bench Press", "Chest", "Barbell"),
        ExerciseDef("Clap Push Up", "Chest", "Bodyweight"),
        ExerciseDef("Cable Middle Fly", "Chest", "Cable"),
        ExerciseDef("Wide Push Up", "Chest", "Bodyweight"),
        ExerciseDef("Plyo Push Up", "Chest", "Bodyweight"),
        ExerciseDef("Dumbbell Straight Arm Pullover", "Chest", "Dumbbells"),
        ExerciseDef("Deadlift", "Back", "Barbell"),
        ExerciseDef("Barbell Row", "Back", "Barbell"),
        ExerciseDef("Pull-Up", "Back", "Bodyweight"),
        ExerciseDef("Lat Pulldown", "Back", "Cable"),
        ExerciseDef("Seated Cable Row", "Back", "Cable"),
        ExerciseDef("T-Bar Row", "Back", "Barbell"),
        ExerciseDef("Chin-Up", "Back", "Bodyweight"),
        ExerciseDef("Wide Grip Pull-Up", "Back", "Bodyweight"),
        ExerciseDef("Cable Straight Arm Pulldown", "Back", "Cable"),
        ExerciseDef("Dumbbell One Arm Row", "Back", "Dumbbells"),
        ExerciseDef("Inverted Row", "Back", "Bodyweight"),
        ExerciseDef("Cable Underhand Pulldown", "Back", "Cable"),
        ExerciseDef("Cable Lateral Pulldown", "Back", "Cable"),
        ExerciseDef("Cable High Row", "Back", "Cable"),
        ExerciseDef("Barbell Pendlay Row", "Back", "Barbell"),
        ExerciseDef("Dumbbell Row", "Back", "Dumbbells"),
        ExerciseDef("Cable Seated Wide-Grip Row", "Back", "Cable"),
        ExerciseDef("Overhead Press", "Shoulders", "Barbell"),
        ExerciseDef("Lateral Raise", "Shoulders", "Dumbbells"),
        ExerciseDef("Front Raise", "Shoulders", "Dumbbells"),
        ExerciseDef("Face Pull", "Shoulders", "Cable"),
        ExerciseDef("Arnold Press", "Shoulders", "Dumbbells"),
        ExerciseDef("Rear Delt Fly", "Shoulders", "Dumbbells"),
        ExerciseDef("Dumbbell Shoulder Press", "Shoulders", "Dumbbells"),
        ExerciseDef("Seated Dumbbell Press", "Shoulders", "Dumbbells"),
        ExerciseDef("Cable Lateral Raise", "Shoulders", "Cable"),
        ExerciseDef("Barbell Upright Row", "Shoulders", "Barbell"),
        ExerciseDef("Cable Front Raise", "Shoulders", "Cable"),
        ExerciseDef("Dumbbell Push Press", "Shoulders", "Dumbbells"),
        ExerciseDef("Cable Shoulder Press", "Shoulders", "Cable"),
        ExerciseDef("Dumbbell Cuban Press", "Shoulders", "Dumbbells"),
        ExerciseDef("Dumbbell Lateral Raise", "Shoulders", "Dumbbells"),
        ExerciseDef("Cable Seated Rear Lateral Raise", "Shoulders", "Cable"),
        ExerciseDef("Barbell Curl", "Arms", "Barbell"),
        ExerciseDef("Hammer Curl", "Arms", "Dumbbells"),
        ExerciseDef("Preacher Curl", "Arms", "Dumbbells"),
        ExerciseDef("Tricep Pushdown", "Arms", "Cable"),
        ExerciseDef("Skull Crusher", "Arms", "Barbell"),
        ExerciseDef("Dips", "Arms", "Bodyweight"),
        ExerciseDef("Concentration Curl", "Arms", "Dumbbells"),
        ExerciseDef("Cable Bicep Curl", "Arms", "Cable"),
        ExerciseDef("Dumbbell Incline Curl", "Arms", "Dumbbells"),
        ExerciseDef("EZ Bar Curl", "Arms", "EZ Bar"),
        ExerciseDef("Barbell Reverse Curl", "Arms", "Barbell"),
        ExerciseDef("Cable Hammer Curl", "Arms", "Cable"),
        ExerciseDef("EZ Bar Preacher Curl", "Arms", "EZ Bar"),
        ExerciseDef("Dumbbell Preacher Curl", "Arms", "Dumbbells"),
        ExerciseDef("Dumbbell Alternate Biceps Curl", "Arms", "Dumbbells"),
        ExerciseDef("EZ Bar Reverse Curl", "Arms", "EZ Bar"),
        ExerciseDef("Dumbbell Bicep Curl", "Arms", "Dumbbells"),
        ExerciseDef("Close-Grip Bench Press", "Arms", "Barbell"),
        ExerciseDef("Dumbbell Kickback", "Arms", "Dumbbells"),
        ExerciseDef("Cable Overhead Tricep Extension", "Arms", "Cable"),
        ExerciseDef("Overhead Tricep Extension", "Arms", "Dumbbells"),
        ExerciseDef("Diamond Push-Up", "Arms", "Bodyweight"),
        ExerciseDef("Close-Grip Push-Up", "Arms", "Bodyweight"),
        ExerciseDef("Bench Dip", "Arms", "Bodyweight"),
        ExerciseDef("EZ Bar Standing French Press", "Arms", "EZ Bar"),
        ExerciseDef("EZ Bar JM Bench Press", "Arms", "EZ Bar"),
        ExerciseDef("Cable Tricep Pushdown V-Bar", "Arms", "Cable"),
        ExerciseDef("Squat", "Legs", "Barbell"),
        ExerciseDef("Leg Press", "Legs", "Machine"),
        ExerciseDef("Romanian Deadlift", "Legs", "Barbell"),
        ExerciseDef("Leg Curl", "Legs", "Machine"),
        ExerciseDef("Leg Extension", "Legs", "Machine"),
        ExerciseDef("Calf Raise", "Legs", "Machine"),
        ExerciseDef("Bulgarian Split Squat", "Legs", "Dumbbells"),
        ExerciseDef("Hip Thrust", "Legs", "Dumbbells"),
        ExerciseDef("Barbell Front Squat", "Legs", "Barbell"),
        ExerciseDef("Barbell Lunge", "Legs", "Barbell"),
        ExerciseDef("Barbell Good Morning", "Legs", "Barbell"),
        ExerciseDef("Dumbbell Lunge", "Legs", "Dumbbells"),
        ExerciseDef("Dumbbell Goblet Squat", "Legs", "Dumbbells"),
        ExerciseDef("Dumbbell Step-Up", "Legs", "Dumbbells"),
        ExerciseDef("Dumbbell Romanian Deadlift", "Legs", "Dumbbells"),
        ExerciseDef("Jump Squat", "Legs", "Bodyweight"),
        ExerciseDef("Walking Lunge", "Legs", "Bodyweight"),
        ExerciseDef("Kettlebell Swing", "Legs", "Kettlebell"),
        ExerciseDef("Kettlebell Goblet Squat", "Legs", "Kettlebell"),
        ExerciseDef("Single Leg Deadlift", "Legs", "Dumbbells"),
        ExerciseDef("Barbell Sumo Deadlift", "Legs", "Barbell"),
        ExerciseDef("Barbell Reverse Lunge", "Legs", "Barbell"),
        ExerciseDef("Barbell Step-Up", "Legs", "Barbell"),
        ExerciseDef("Sled Hack Squat", "Legs", "Sled Machine"),
        ExerciseDef("Kettlebell Turkish Get Up", "Legs", "Kettlebell"),
        ExerciseDef("Kettlebell Front Squat", "Legs", "Kettlebell"),
        ExerciseDef("Split Squat", "Legs", "Bodyweight"),
        ExerciseDef("Plank", "Core", "Bodyweight"),
        ExerciseDef("Crunch", "Core", "Bodyweight"),
        ExerciseDef("Russian Twist", "Core", "Bodyweight"),
        ExerciseDef("Hanging Leg Raise", "Core", "Bodyweight"),
        ExerciseDef("Ab Rollout", "Core", "Cable"),
        ExerciseDef("Cable Woodchop", "Core", "Cable"),
        ExerciseDef("Dead Bug", "Core", "Bodyweight"),
        ExerciseDef("Reverse Crunch", "Core", "Bodyweight"),
        ExerciseDef("Side Plank", "Core", "Bodyweight"),
        ExerciseDef("Lying Leg Raise", "Core", "Bodyweight"),
        ExerciseDef("Cable Crunch", "Core", "Cable"),
        ExerciseDef("Cross Body Crunch", "Core", "Bodyweight"),
        ExerciseDef("Sit-Up", "Core", "Bodyweight"),
        ExerciseDef("Seated Leg Raise", "Core", "Bodyweight"),
        ExerciseDef("Decline Sit-Up", "Core", "Bodyweight"),
        ExerciseDef("Hanging Knee Raise", "Core", "Bodyweight"),
        ExerciseDef("Cable Seated Twist", "Core", "Cable"),
        ExerciseDef("Jackknife Sit-Up", "Core", "Bodyweight"),
        ExerciseDef("Front Plank With Twist", "Core", "Bodyweight"),
        ExerciseDef("Barbell Shrugs", "Traps", "Barbell"),
        ExerciseDef("Dumbbell Shrugs", "Traps", "Dumbbells"),
        ExerciseDef("Cable Shrugs", "Traps", "Cable"),
        ExerciseDef("Barbell Shrug", "Traps", "Barbell"),
        ExerciseDef("Barbell Wrist Curl", "Forearms", "Barbell"),
        ExerciseDef("Barbell Reverse Wrist Curl", "Forearms", "Barbell"),
        ExerciseDef("Farmer's Walk", "Forearms", "Dumbbells"),
        ExerciseDef("Finger Curls", "Forearms", "Barbell"),
        ExerciseDef("Dumbbell Wrist Curl", "Forearms", "Dumbbells"),
        ExerciseDef("Cable Wrist Curl", "Forearms", "Cable"),
        ExerciseDef("Dumbbell Reverse Wrist Curl", "Forearms", "Dumbbells"),
        ExerciseDef("Neck Side Stretch", "Neck", "Bodyweight"),
        ExerciseDef("Side Push Neck Stretch", "Neck", "Bodyweight"),
        ExerciseDef("Treadmill", "Cardio", "Machine"),
        ExerciseDef("Stationary Bike", "Cardio", "Machine"),
        ExerciseDef("Rowing Machine", "Cardio", "Machine"),
        ExerciseDef("Jump Rope", "Cardio", "Bodyweight"),
        ExerciseDef("Stair Climber", "Cardio", "Machine"),
        ExerciseDef("Elliptical", "Cardio", "Machine"),
        ExerciseDef("Burpee", "Cardio", "Bodyweight"),
        ExerciseDef("Mountain Climber", "Cardio", "Bodyweight"),
        ExerciseDef("Jumping Jack", "Cardio", "Bodyweight"),
        ExerciseDef("Bear Crawl", "Cardio", "Bodyweight"),
        ExerciseDef("Smith Machine Bench Press", "Chest", "Smith Machine"),
        ExerciseDef("Smith Machine Squat", "Legs", "Smith Machine"),
        ExerciseDef("Smith Machine Shoulder Press", "Shoulders", "Smith Machine"),
        ExerciseDef("Smith Machine Incline Bench Press", "Chest", "Smith Machine"),
        ExerciseDef("Smith Machine Shrugs", "Traps", "Smith Machine"),
        ExerciseDef("Lever Chest Press", "Chest", "Machine"),
        ExerciseDef("Lever Seated Fly", "Chest", "Machine"),
        ExerciseDef("Lever Shoulder Press", "Shoulders", "Machine"),
        ExerciseDef("Lever Lateral Raise", "Shoulders", "Machine"),
        ExerciseDef("Lever Seated Leg Curl", "Legs", "Machine"),
        ExerciseDef("Lever Leg Extension", "Legs", "Machine"),
        ExerciseDef("Lever Seated Calf Raise", "Legs", "Machine"),
        ExerciseDef("Lever Bent Over Row", "Back", "Machine"),
        ExerciseDef("Lever Seated Row", "Back", "Machine"),
        ExerciseDef("Lever T-Bar Row", "Back", "Machine"),
        ExerciseDef("Lever Deadlift", "Legs", "Machine"),
        ExerciseDef("Stability Ball Crunch", "Core", "Stability Ball"),
        ExerciseDef("EZ Bar Lying Bent Arms Pullover", "Back", "EZ Bar"),
        ExerciseDef("EZ Bar Seated Triceps Extension", "Arms", "EZ Bar")
    )

    val defaultTemplates = listOf(
        WorkoutTemplate("Push Day", listOf(
            TemplateExercise("Chest", ExerciseDefinition("Bench Press", "Chest", "Barbell")),
            TemplateExercise("Chest", ExerciseDefinition("Incline Bench Press", "Chest", "Barbell")),
            TemplateExercise("Chest", ExerciseDefinition("Dumbbell Fly", "Chest", "Dumbbells")),
            TemplateExercise("Shoulders", ExerciseDefinition("Overhead Press", "Shoulders", "Barbell")),
            TemplateExercise("Shoulders", ExerciseDefinition("Lateral Raise", "Shoulders", "Dumbbells")),
            TemplateExercise("Arms", ExerciseDefinition("Tricep Pushdown", "Arms", "Cable"))
        )),
        WorkoutTemplate("Pull Day", listOf(
            TemplateExercise("Back", ExerciseDefinition("Deadlift", "Back", "Barbell")),
            TemplateExercise("Back", ExerciseDefinition("Barbell Row", "Back", "Barbell")),
            TemplateExercise("Back", ExerciseDefinition("Pull-Up", "Back", "Bodyweight")),
            TemplateExercise("Back", ExerciseDefinition("Lat Pulldown", "Back", "Cable")),
            TemplateExercise("Arms", ExerciseDefinition("Barbell Curl", "Arms", "Barbell")),
            TemplateExercise("Shoulders", ExerciseDefinition("Face Pull", "Shoulders", "Cable"))
        )),
        WorkoutTemplate("Leg Day", listOf(
            TemplateExercise("Legs", ExerciseDefinition("Squat", "Legs", "Barbell")),
            TemplateExercise("Legs", ExerciseDefinition("Romanian Deadlift", "Legs", "Barbell")),
            TemplateExercise("Legs", ExerciseDefinition("Leg Press", "Legs", "Machine")),
            TemplateExercise("Legs", ExerciseDefinition("Leg Curl", "Legs", "Machine")),
            TemplateExercise("Legs", ExerciseDefinition("Leg Extension", "Legs", "Machine")),
            TemplateExercise("Legs", ExerciseDefinition("Calf Raise", "Legs", "Machine"))
        )),
        WorkoutTemplate("Upper Body", listOf(
            TemplateExercise("Chest", ExerciseDefinition("Bench Press", "Chest", "Barbell")),
            TemplateExercise("Back", ExerciseDefinition("Barbell Row", "Back", "Barbell")),
            TemplateExercise("Shoulders", ExerciseDefinition("Overhead Press", "Shoulders", "Barbell")),
            TemplateExercise("Arms", ExerciseDefinition("Barbell Curl", "Arms", "Barbell")),
            TemplateExercise("Arms", ExerciseDefinition("Tricep Pushdown", "Arms", "Cable"))
        )),
        WorkoutTemplate("Full Body", listOf(
            TemplateExercise("Chest", ExerciseDefinition("Bench Press", "Chest", "Barbell")),
            TemplateExercise("Back", ExerciseDefinition("Barbell Row", "Back", "Barbell")),
            TemplateExercise("Legs", ExerciseDefinition("Squat", "Legs", "Barbell")),
            TemplateExercise("Shoulders", ExerciseDefinition("Overhead Press", "Shoulders", "Barbell")),
            TemplateExercise("Core", ExerciseDefinition("Plank", "Core", "Bodyweight"))
        ))
    )
}

data class ExerciseDefinition(val name: String, val group: String, val equipment: String = "") {
    val nume: String get() = name
}
